# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
dizi=np.array([12,35,98,46,77])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sirali_dizi=np.sort(dizi)
print("Sıraı dizi:", sirali_dizi)


Sıraı dizi: [12 35 46 77 98]


# Problem 2

In [9]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1=np.array([10,15,30,45,60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3=np.arange(50,101,5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4=np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5=np.ones(10)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6=np.linspace(0,100,5)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7=np.random.uniform(10,30,5)


# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8=np.random.randint(-1,1,10)


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris=np.random.randint(10,50,(3,5))


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam=matris.sum(axis=1)
sutun_toplam=matris.sum(axis=0)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
maks = matris.max()
minn = matris.min()
ortalama = matris.mean()


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
indeks = np.unravel_index(matris.argmax(), matris.shape)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi9 = np.arange(10, 21)
ilk_uc = dizi9[:3]


# 14- Üretilen dizinin elemanlarını tersten yazdırın.
ters = dizi9[::-1]


# 15- Üretilen matrisin ilk satırını seçiniz.
ilk_satır=matris[0]


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman = matris[1, 2]


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_sutun = matris[:, 0]

# 18- Üretilen matrisin her bir elemanının karesini alınız.
kare_matris = matris ** 2


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
np.random.seed(0)  # sabit rastgelelik için
matris2 = np.random.randint(-50, 51, (3, 5))
cift_pozitif = matris2[(matris2 > 0) & (matris2 % 2 == 0)]

import numpy as np

# 1
dizi1 = np.array([10, 15, 30, 45, 60])
print("1- Dizi1:", dizi1)

# 2
dizi2 = np.arange(5, 16)
print("2- Dizi2:", dizi2)

# 3
dizi3 = np.arange(50, 101, 5)
print("3- Dizi3:", dizi3)

# 4
dizi4 = np.zeros(10)
print("4- 10 elemanlı sıfır dizisi:", dizi4)

# 5
dizi5 = np.ones(10)
print("5- 10 elemanlı bir dizisi:", dizi5)

# 6
dizi6 = np.linspace(0, 100, 5)
print("6- Eşit aralıklı 5 sayı:", dizi6)

# 7
dizi7 = np.random.randint(10, 30, 5)
print("7- Rastgele 5 tamsayı (10-30):", dizi7)

# 8
dizi8 = np.random.uniform(-1, 1, 10)
print("8- [-1, 1] arasında 10 sayı:", dizi8)

# 9
matris = np.random.randint(10, 50, (3, 5))
print("9- (3x5) Matris:\n", matris)

# 10
print("10- Satır toplamları:", matris.sum(axis=1))
print("    Sütun toplamları:", matris.sum(axis=0))

# 11
print("11- En büyük:", matris.max())
print("     En küçük:", matris.min())
print("     Ortalama:", matris.mean())

# 12
print("12- En büyük değerin indeksi:", np.unravel_index(matris.argmax(), matris.shape))

# 13
dizi9 = np.arange(10, 21)
print("13- İlk 3 eleman:", dizi9[:3])

# 14
print("14- Ters yazım:", dizi9[::-1])

# 15
print("15- İlk satır:", matris[0])

# 16
print("16- 2. satır 3. sütun elemanı:", matris[1, 2])

# 17
print("17- Her satırın ilk elemanı:", matris[:, 0])

# 18
print("18- Elemanların kareleri:\n", matris ** 2)

# 19
matris2 = np.random.randint(-50, 51, (3, 5))
pozitif_ciftler = matris2[(matris2 > 0) & (matris2 % 2 == 0)]
print("19- Yeni matris:\n", matris2)
print("    Pozitif çift sayılar:", pozitif_ciftler)



1- Dizi1: [10 15 30 45 60]
2- Dizi2: [ 5  6  7  8  9 10 11 12 13 14 15]
3- Dizi3: [ 50  55  60  65  70  75  80  85  90  95 100]
4- 10 elemanlı sıfır dizisi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5- 10 elemanlı bir dizisi: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6- Eşit aralıklı 5 sayı: [  0.  25.  50.  75. 100.]
7- Rastgele 5 tamsayı (10-30): [11 16 17 24 27]
8- [-1, 1] arasında 10 sayı: [ 0.85119328 -0.85792788 -0.8257414  -0.95956321  0.66523969  0.5563135
  0.7400243   0.95723668  0.59831713 -0.07704128]
9- (3x5) Matris:
 [[29 29 24 49 42]
 [11 19 42 41 20]
 [33 45 21 38 44]]
10- Satır toplamları: [173 133 181]
    Sütun toplamları: [ 73  93  87 128 106]
11- En büyük: 49
     En küçük: 11
     Ortalama: 32.46666666666667
12- En büyük değerin indeksi: (np.int64(0), np.int64(3))
13- İlk 3 eleman: [10 11 12]
14- Ters yazım: [20 19 18 17 16 15 14 13 12 11 10]
15- İlk satır: [29 29 24 49 42]
16- 2. satır 3. sütun elemanı: 42
17- Her satırın ilk elemanı: [29 11 33]
18- Elemanların kareleri:
 [[ 841  84