# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [18]:
pip install numpy 


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 1.9 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [19]:

import numpy as np

matris = np.random.randint(0, 10, size=5)
print(matris)

print(matris.shape)

matris = matris.reshape(5, 1)  
print(matris)

print(matris.ndim)


[9 9 2 4 1]
(5,)
[[9]
 [9]
 [2]
 [4]
 [1]]
2


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [20]:
import numpy as np

tek_sayilar = np.arange(1, 10, 2)  

matris = tek_sayilar.reshape(1, 5)  
print("Matris:\n", matris)
matris1, matris2 = np.hsplit(matris, [2])  

print("Matris 1:\n", matris1)
print("Matris 2:\n", matris2)
birlesmis_matris = np.hstack((matris1, matris2))

print("Birleşmiş Matris:\n", birlesmis_matris)



Matris:
 [[1 3 5 7 9]]
Matris 1:
 [[1 3]]
Matris 2:
 [[5 7 9]]
Birleşmiş Matris:
 [[1 3 5 7 9]]


# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [21]:
import numpy as np

sayilar = np.arange(5, 101, 2)

matris = np.random.choice(sayilar, 10, replace=False)
print("Matris:", matris)
print("Matrisin boyutu (shape):", matris.shape)
print("Matrisin boyut sayısı (ndim):", matris.ndim)
print("Matrisin eleman sayısı (size):", matris.size)
print("Matrisin veri tipi (dtype):", matris.dtype)




Matris: [47 95 65 71 79 99 15 11 45 91]
Matrisin boyutu (shape): (10,)
Matrisin boyut sayısı (ndim): 1
Matrisin eleman sayısı (size): 10
Matrisin veri tipi (dtype): int64
